/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ServiceInformation;
import io.swagger.model.SingleEndpointConfiguration;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-09-21T16:14:04.338Z")

@Api(value = "services", description = "the services API")
public interface ServicesApi {

    @ApiOperation(value = "Find specyfication of concrete endpoint", notes = "Returns a single function description", response = SingleEndpointConfiguration.class, tags={ "services", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = SingleEndpointConfiguration.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied", response = Void.class),
        @ApiResponse(code = 404, message = "Endpoint not found", response = Void.class) })
    
    @RequestMapping(value = "/services/{service_name}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<SingleEndpointConfiguration> funcfuncId(@ApiParam(value = "ID of func to return",required=true ) @PathVariable("service_name") String serviceName);


    @ApiOperation(value = "Returns api specyfication", notes = "Returns all informations about how to run calculations on microservice", response = ServiceInformation.class, tags={ "services", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = ServiceInformation.class),
        @ApiResponse(code = 400, message = "Invalid status value", response = Void.class) })
    
    @RequestMapping(value = "/services",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ServiceInformation> servicesGet();

}
